ifeq ($(ANDROID_BUILD_TOP),)
ANDROID_BUILD_TOP := $(srctree)/..
endif

# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8475-modules/motorola/include
EXTRA_CFLAGS += -I$(KERNEL_SRC)
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel_platform/msm-kernel/net/qrtr/
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8475-modules/motorola/drivers/power_monitor

KBUILD_EXTRA_SYMBOLS := $(CURDIR)/../../kernel_platform/msm-kernel/Module.symvers

obj-m += sys_monitor.o

sys_monitor-y := main.o sleep.o

